In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
#Keras
import keras
from keras import models
from keras import layers
import os
from os import listdir
from os.path import isfile, join
from sklearn.metrics import accuracy_score

In [206]:
# reading dataset from csv

data = pd.read_csv('/content/drive/MyDrive/last_dataframe/dataframe.csv')
data.head()

song_name  chroma_stft  ...     mfcc20  polarity
0       3 Doors Down - Here Without You.mp3     0.289081  ...  -5.975074         1
1   Adam Lambert - Whataya Want from Me.mp3     0.355750  ...   3.940006         1
2                    Adele - Easy On Me.mp3     0.262327  ...  10.148050         1
3         Adele - Make You Feel My Love.mp3     0.292123  ...  -1.815166         1
4  Alan Walker, Ava Max - Alone, Pt. II.mp3     0.338901  ...   6.590695         0

[5 rows x 28 columns]

In [207]:
data = data.sample(frac = 1, random_state = 10).reset_index(drop=True)
data.head()

song_name  ...  polarity
0  Bahamas, Madison Cunningham - Be My Witness (f...  ...         0
1        The Offspring - The Kids Aren't Alright.mp3  ...         0
2                           Faith Hill - Breathe.mp3  ...         0
3         The Skatalites - Eastern Standard Time.mp3  ...         0
4  Albert Collins - Blue Monday Hangover - Remast...  ...         1

[5 rows x 28 columns]

In [208]:
data.shape

(1641, 28)

In [209]:
len(data)

1641

In [210]:
"""
for i in range(70,90):
    print(data["song_name"][i])
"""

'\nfor i in range(70,90):\n    print(data["song_name"][i])\n'

In [211]:
y_train = [1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,1,0,1,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0]
X_train = data.iloc[0:50, 1:]
validation_y = [1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0]
validation_x = data.iloc[50:70, 1:]
X_test = data.iloc[70:, 1:]

y_train = np.array(y_train)
validation_y = np.array(validation_y)

In [212]:
X_train.head()

chroma_stft      rmse  spectral_centroid  ...    mfcc19    mfcc20  polarity
0     0.342932  0.163363        1569.343678  ... -4.445862  0.289576         0
1     0.410226  0.235695        2432.832611  ... -4.360817  1.856898         0
2     0.324153  0.148818        2436.451795  ... -4.044796 -0.622057         0
3     0.442773  0.123286        2396.140950  ... -3.218498  4.762727         0
4     0.384747  0.133702        2171.121864  ... -2.910830  2.285146         1

[5 rows x 27 columns]

In [213]:
# normalizing
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
validation_x = scaler.fit_transform(validation_x)
X_test = scaler.fit_transform(X_test)

In [214]:
X_train

array([[-0.50639769, -0.1815294 , -0.91292609, ..., -0.26557168,
        -0.09480946, -1.12815215],
       [ 0.67819184,  0.91819658,  0.75071039, ..., -0.23782631,
         0.37955695, -1.12815215],
       [-0.83695821, -0.40267824,  0.75768327, ..., -0.13472678,
        -0.37072465, -1.12815215],
       ...,
       [ 0.15728768,  1.330072  , -0.5172284 , ..., -1.51033658,
        -0.89541798, -1.12815215],
       [-0.43316358,  2.50565008, -0.64857604, ..., -0.57207649,
        -0.27400438, -1.12815215],
       [-1.28378677, -0.13971087, -1.51638157, ...,  2.83159718,
        -1.5455643 , -1.12815215]])

In [215]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1, metric="minkowski")
knn.fit(X_train, y_train)                             
y_pred = knn.predict(validation_x)

print(y_pred)
unique, counts = np.unique(y_pred, return_counts=True)
dict(zip(unique, counts))

[0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0]


{0: 12, 1: 8}

In [216]:
accuracy_score(validation_y, y_pred)

0.55

In [217]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(validation_x)

print(y_pred)
unique, counts = np.unique(y_pred, return_counts=True)
dict(zip(unique, counts))

[0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0]


{0: 17, 1: 3}

In [218]:
accuracy_score(validation_y, y_pred)

0.8

In [219]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train)
y_pred = logr.predict(validation_x)

print(y_pred)
unique, counts = np.unique(y_pred, return_counts=True)
dict(zip(unique, counts))

[1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0]


{0: 14, 1: 6}

In [220]:
accuracy_score(validation_y, y_pred)

0.85

In [221]:
model = models.Sequential()
model.add(layers.Dense(20, activation='relu', input_shape=(X_train.shape[1],)))
#model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [222]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [223]:
history = model.fit(X_train,
                    y_train,
                    epochs=50,
                    batch_size=4,
                    validation_data=(validation_x, validation_y))

Epoch 1/50
13/13 [==============================] - 1s 16ms/step - loss: 1.0003 - accuracy: 0.4000 - val_loss: 0.9095 - val_accuracy: 0.2500
Epoch 2/50
13/13 [==============================] - 0s 5ms/step - loss: 0.8773 - accuracy: 0.4400 - val_loss: 0.8272 - val_accuracy: 0.3500
Epoch 3/50
13/13 [==============================] - 0s 5ms/step - loss: 0.7928 - accuracy: 0.4800 - val_loss: 0.7549 - val_accuracy: 0.4000
Epoch 4/50
13/13 [==============================] - 0s 5ms/step - loss: 0.7227 - accuracy: 0.5200 - val_loss: 0.6937 - val_accuracy: 0.6000
Epoch 5/50
13/13 [==============================] - 0s 6ms/step - loss: 0.6650 - accuracy: 0.6000 - val_loss: 0.6434 - val_accuracy: 0.6000
Epoch 6/50
13/13 [==============================] - 0s 5ms/step - loss: 0.6178 - accuracy: 0.6600 - val_loss: 0.6094 - val_accuracy: 0.7000
Epoch 7/50
13/13 [==============================] - 0s 4ms/step - loss: 0.5774 - accuracy: 0.7200 - val_loss: 0.5816 - val_accuracy: 0.7000
Epoch 8/50
13/13 [=

In [224]:
y_pred = list()
for i in model.predict(validation_x):
    if i > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)
unique, counts = np.unique(y_pred, return_counts=True)
dict(zip(unique, counts))

{0: 15, 1: 5}

In [226]:
names = pd.DataFrame(data.iloc[70:, :1].values, columns = ["song_names"])
names

song_names
0                            Collin Raye - Love, Me.mp3
1                      Barrington Levy - Sensimilea.mp3
2     Thelonious Monk Trio - Blue Monk - Rudy Van Ge...
3                                Frazey Ford - Saul.mp3
4                         Billie Holiday - Solitude.mp3
...                                                 ...
1566  Peter, Paul and Mary - Don't Think Twice, It's...
1567                          Dolly Parton - Jolene.mp3
1568  Miles Davis Quintet - Solar - Rudy Van Gelder ...
1569                 Tiësto, BT - Love Comes Again.mp3
1570  Hound Dog Taylor - Give Me Back My Wig - Remas...

[1571 rows x 1 columns]

In [227]:
values = pd.DataFrame(model.predict(X_test), columns = ["values"])
values

values
0     0.675442
1     0.016516
2     0.888607
3     0.147888
4     0.160417
...        ...
1566  0.077907
1567  0.448638
1568  0.044151
1569  0.049523
1570  0.143394

[1571 rows x 1 columns]

In [228]:
recommend_df = pd.concat([names, values], axis=1)
recommend_df

song_names    values
0                            Collin Raye - Love, Me.mp3  0.675442
1                      Barrington Levy - Sensimilea.mp3  0.016516
2     Thelonious Monk Trio - Blue Monk - Rudy Van Ge...  0.888607
3                                Frazey Ford - Saul.mp3  0.147888
4                         Billie Holiday - Solitude.mp3  0.160417
...                                                 ...       ...
1566  Peter, Paul and Mary - Don't Think Twice, It's...  0.077907
1567                          Dolly Parton - Jolene.mp3  0.448638
1568  Miles Davis Quintet - Solar - Rudy Van Gelder ...  0.044151
1569                 Tiësto, BT - Love Comes Again.mp3  0.049523
1570  Hound Dog Taylor - Give Me Back My Wig - Remas...  0.143394

[1571 rows x 2 columns]

In [229]:
recommend_df = recommend_df.sort_values("values", ascending=False).reset_index(drop=True)
recommend_df

song_names    values
0                          Ava Max - Kings & Queens.mp3  0.998770
1                 Mariah Carey - We Belong Together.mp3  0.998225
2              Alan Walker, Ava Max - Alone, Pt. II.mp3  0.997595
3          Doja Cat, SZA - Kiss Me More (feat. SZA).mp3  0.997523
4                                    Ava Max - Salt.mp3  0.997501
...                                                 ...       ...
1566  Fleet Foxes - I'm Not My Season - Solstice Ver...  0.002782
1567  Stealers Wheel - Stuck In The Middle With You.mp3  0.002470
1568               Elmore James - The Sky Is Crying.mp3  0.001828
1569                    Bad Brains - Banned In D.C..mp3  0.001671
1570    Louis Armstrong, The Commanders - Cool Yule.mp3  0.000685

[1571 rows x 2 columns]

In [230]:
print("RECOMMENDED SONGS:")
for i in range(10):
    print(recommend_df["song_names"][i])

RECOMMENDED SONGS:
Ava Max - Kings & Queens.mp3
Mariah Carey - We Belong Together.mp3
Alan Walker, Ava Max - Alone, Pt. II.mp3
Doja Cat, SZA - Kiss Me More (feat. SZA).mp3
Ava Max - Salt.mp3
Fabolous, Tamia - Into You.mp3
Farruko - Pepas.mp3
Mariah Carey, JAY-Z - Heartbreaker (feat. Jay-Z).mp3
Ariana Grande - positions.mp3
Lil Nas X - MONTERO (Call Me By Your Name).mp3
